import type { NextConfig } from "next";

const heliTourSlugs = [
  "annapurna-base-camp-heli-landing-tour",
  "mardi-heli-tour",
  "poonhill-ghandruk-helicopter-tour",
  "kapuche-helicopter-tour",
  "kori-helicopter-tour",
  "muktinath-helicopter-tour",
  "heli-tour-north-annapurna-base-camp",
  "tilicho-lake-helicopter-tour",
  "upper-mustang-helicopter-tour",
  "manang-helicopter-tour",
  "everest-helicopter-tour",
  "rescue-flight-medical-evacuation-and-other-services",
] as const;

const tourSlugs = [
  "australian-camp-day-hike",
  "pokhara-peace-pagoda-hike",
  "sarangkot-australian-camp-to-dhampus-hike",
  "kalikasthan-day-hike",
  "sarangkot-sunrise-hike",
  "kathmandu-day-tour",
  "nagarkot-sunrise-tour",
  "pokhara-lake-tour",
  "pokhara-city-tour",
  "pokhara-day-tour",
  "lumbini-day-tour",
  "best-of-nepal-tour",
  "kathmandu-pokhara-chitwan-tour",
  "birding-tour-in-pokhara-nepal",
  "bardiya-national-park-safari",
  "chitwan-national-park-safari",
  "begnas-lake-day-hike",
  "naudanda-day-hike",
] as const;

const trekSlugs = [
  "upper-mustang-trek-nepal",
  "annapurna-base-camp-trek",
  "annapurna-circuit-trek",
  "mardi-himal-trek",
  "annapurna-north-base-camp-trek",
  "annapurna-sanctuary-trek",
  "khopra-trek-nepal",
  "poonhill-trek-from-pokhara",
  "tilicho-lake-trek",
  "mohare-danda-trek",
  "nar-phu-valley-trek",
  "panchase-trek",
  "ghandruk-village-trek",
  "kapuche-lake-trek",
  "kori-himal-trek",
  "korcha-trek",
  "sikles-village-trek",
  "royal-trek-nepal",
  "four-peaks-trek-annapurna-region",
  "upper-mustang-jeep-tour",
  "lower-mustang-trek-nepal",
  "hidden-lake-trek-nepal",
  "kajin-sara-trek",
  "base-camp-annapurna-cost",
  "namunla-trek",
  "short-annapurna-base-camp-trek",
  "teri-la-pass-trek",
  "annapurna-base-camp-trek-13-days",
  "three-peaks-trek",
  "tiji-festival-tour",
  "everest-base-camp-trek",
  "everest-high-passes-trek",
  "gokyo-lake-trek",
  "pikey-peak-trek",
  "tsum-valley-trek",
  "manaslu-with-tsum-valley-trek",
  "manaslu-circuit-trek",
  "bhimtang-trek",
  "manaslu-circuit-trekking",
  "dhorpatan-trek-with-gurjakhani",
  "rara-lake-trek",
  "lower-dolpa-trek-nepal",
  "upper-dolpo-trek",
  "gosaikunda-trek-nepal",
  "helambu-trek",
  "langtang-valley-trek",
  "tamang-heritage-trek",
  "langtang-trek-cost-itinerary-route-map",
  "dhaulagiri-circuit-trek",
  "tibet-kailash-mansarovar-tour",
  "bhutan-4-night-5-days-tour",
  "bhutan-tour-6-night-7-days",
  "bhutan-tours-and-trekking-8-days-itinerary",
  "kailash-mansarovar-everest-base-camp-tour",
  "kanchenjunga-circuit-trek",
] as const;

const nextConfig: NextConfig = {
  /* config options here */
  reactCompiler: true,
  devIndicators: false,
  async redirects() {
    return [
      {
        source: "/heli-tours",
        destination: "/tours",
        permanent: true,
      },
      {
        source: "/day-hike-in-nepal",
        destination: "/trip",
        permanent: true,
      },
      {
        source: "/short-treks-from-pokhara",
        destination: "/trip",
        permanent: true,
      },
      {
        source: "/nepal-tours",
        destination: "/trip",
        permanent: true,
      },
      {
        source: "/day-tour",
        destination: "/trip",
        permanent: true,
      },
      {
        source: "/multi-days-tour",
        destination: "/trip",
        permanent: true,
      },
      {
        source: "/bird-tour-nepal",
        destination: "/trip",
        permanent: true,
      },
      ...heliTourSlugs.map((slug) => ({
        source: `/${slug}`,
        destination: `/tours/${slug}`,
        permanent: true as const,
      })),
      ...tourSlugs.map((slug) => ({
        source: `/${slug}`,
        destination: `/trip/${slug}`,
        permanent: true as const,
      })),
      ...trekSlugs.map((slug) => ({
        source: `/${slug}`,
        destination: `/trip/${slug}`,
        permanent: true as const,
      })),
      {
        source: "/trekking-and-hiking",
        destination: "/trip",
        permanent: true,
      },
      {
        source: "/everest-trekking",
        destination: "/region/everest-region",
        permanent: true,
      },
      {
        source: "/annapurna-trekking",
        destination: "/region/annapurna-region",
        permanent: true,
      },
      {
        source: "/manaslu-trekking",
        destination: "/region/manaslu-region",
        permanent: true,
      },
      {
        source: "/west-nepal-trekking",
        destination: "/region/west-nepal",
        permanent: true,
      },
      {
        source: "/langtang-trekking",
        destination: "/region/langtang-region",
        permanent: true,
      },
      {
        source: "/dhaulagiri-trek",
        destination: "/region/dhaulagiri-region",
        permanent: true,
      },
      {
        source: "/tibet-region",
        destination: "/region/tibet-region",
        permanent: true,
      },
      {
        source: "/kanchenjunga-region",
        destination: "/region/kanchenjunga-region",
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
