import { TbBike, TbDroplet, TbRipple } from "react-icons/tb";

import { BUNGEE_PHOTO, TREK_PHOTO } from "@/constant/photos";
import type { AdventureActivity } from "@/features/site/activity/constant/types";

export const trailActivities: AdventureActivity[] = [
  {
    title: "Rafting in Nepal",
    excerpt:
      "A primer on Nepal's rivers from Pokhara — which run suits a first timer, which needs a few days, and when the water is best.",
    href: "/rafting-in-nepal",
    category: "rafting",
    duration: "Half day+",
    location: "Pokhara & beyond",
    difficulty: "Easy to Moderate",
    price: 45,
    image: TREK_PHOTO,
    icon: TbRipple,
  },
  {
    title: "Trishuli River Rafting",
    excerpt:
      "The classic highway river between Kathmandu and Pokhara. Gentle rapids, big scenery, a good first day on the water.",
    href: "/trishuli-river-rafting",
    category: "rafting",
    duration: "1 day",
    location: "Trishuli River",
    difficulty: "Easy",
    price: 45,
    image: TREK_PHOTO,
    icon: TbRipple,
  },
  {
    title: "Upper Seti River Rafting",
    excerpt:
      "Pokhara's nearest white water. A short drive, a lively half day, and you are back in Lakeside before evening.",
    href: "/upper-seti-river-rafting",
    category: "rafting",
    duration: "Half day",
    location: "Seti River",
    difficulty: "Moderate",
    price: 50,
    image: TREK_PHOTO,
    icon: TbRipple,
  },
  {
    title: "Kali Gandaki River Rafting",
    excerpt:
      "A longer, wilder run through the deepest gorge on earth. Overnight camping on the riverbank if you want it.",
    href: "/kali-gandaki-river-rafting",
    category: "rafting",
    duration: "2–3 days",
    location: "Kali Gandaki",
    difficulty: "Moderate",
    price: 85,
    image: TREK_PHOTO,
    icon: TbRipple,
  },
  {
    title: "Lower Seti River Rafting",
    excerpt:
      "A gentler stretch of the Seti. Suited to families and anyone who wants the river without the bigger rapids.",
    href: "/lower-seti-river-rafting",
    category: "rafting",
    duration: "Half day",
    location: "Seti River",
    difficulty: "Easy",
    price: 40,
    image: TREK_PHOTO,
    icon: TbRipple,
  },
  {
    title: "Marsyangdi River Rafting",
    excerpt:
      "Steep, technical water below the Annapurna circuit road. For people who already know they like rapids.",
    href: "/marsyangdi-river-rafting",
    category: "rafting",
    duration: "1–2 days",
    location: "Marsyangdi River",
    difficulty: "Challenging",
    price: 95,
    image: TREK_PHOTO,
    icon: TbRipple,
  },
  {
    title: "Cycling in Pokhara",
    excerpt:
      "Lakeside to village trails, Begnas and Rupa, and the ridge roads above Sarangkot. Bikes, guides and a packed lunch.",
    href: "/cycling-in-pokhara",
    category: "cycling",
    duration: "Half day",
    location: "Pokhara Valley",
    difficulty: "Easy",
    price: 35,
    image: TREK_PHOTO,
    icon: TbBike,
  },
  {
    title: "Upper Mustang Mountain Biking Tour",
    excerpt:
      "Jeep-road and singletrack through the former kingdom of Lo. Wind-carved cliffs, cave villages, and a high desert sky.",
    href: "/uppermustang-biking-mtb-tour",
    category: "cycling",
    duration: "10 days",
    location: "Upper Mustang",
    difficulty: "Challenging",
    price: 890,
    image: TREK_PHOTO,
    icon: TbBike,
  },
  {
    title: "Annapurna Circuit Mountain Bike Tour",
    excerpt:
      "The classic circuit on two wheels — rice terraces, high passes and the long descent toward Jomsom.",
    href: "/annapurna-bike-tour",
    category: "cycling",
    duration: "12 days",
    location: "Annapurna Circuit",
    difficulty: "Challenging",
    price: 750,
    image: TREK_PHOTO,
    icon: TbBike,
  },
  {
    title: "Pokhara Canyoning in Lwang Village",
    excerpt:
      "Rappels, jumps and slides in a gorge above Lwang. A full day out, still close enough to sleep in Pokhara.",
    href: "/canyoning-in-pokhara",
    category: "canyoning",
    duration: "Full day",
    location: "Lwang Village",
    difficulty: "Moderate",
    price: 80,
    image: BUNGEE_PHOTO,
    icon: TbDroplet,
  },
  {
    title: "Canyoning in Jalbire Jharana",
    excerpt:
      "A waterfall canyon with longer rappels and deeper pools. For people who liked Lwang and want a bigger day.",
    href: "/canyoning-in-jalbire",
    category: "canyoning",
    duration: "Full day",
    location: "Jalbire Jharana",
    difficulty: "Moderate",
    price: 75,
    image: BUNGEE_PHOTO,
    icon: TbDroplet,
  },
];
