import {
  TbFlag,
  TbMountain,
  TbRoute,
  TbSunrise,
  TbTent,
} from "react-icons/tb";

import { TREK_PHOTO, WOMEN_TREK_PHOTO } from "@/constant/photos";
import type { Trek } from "@/features/site/home/constant/trek";

export const popularTreks: Trek[] = [
  {
    title: "Annapurna Base Camp Trek",
    days: "7 Days",
    href: "/trip/annapurna-base-camp-trek",
    rating: 4.9,
    reviews: 86,
    difficulty: "Moderate",
    altitude: "4,130 m",
    season: "Mar to May, Sep to Nov",
    price: 475,
    icon: TbMountain,
    image: TREK_PHOTO,
  },
  {
    title: "Mardi Himal Trek",
    days: "5 Days",
    href: "/trip/mardi-himal-trek",
    rating: 4.9,
    reviews: 61,
    difficulty: "Moderate",
    altitude: "4,500 m",
    season: "Mar to May, Oct to Dec",
    price: 385,
    icon: TbMountain,
    image: WOMEN_TREK_PHOTO,
  },
  {
    title: "Ghorepani Poon Hill Trek",
    days: "4 Days",
    href: "/trip/poonhill-trek-from-pokhara",
    rating: 4.8,
    reviews: 94,
    difficulty: "Easy to Moderate",
    altitude: "3,210 m",
    season: "All year",
    price: 295,
    icon: TbSunrise,
    image: TREK_PHOTO,
  },
  {
    title: "Khopra Danda Trek",
    days: "8 Days",
    href: "/trip/khopra-trek-nepal",
    rating: 4.9,
    reviews: 52,
    difficulty: "Moderate",
    altitude: "4,660 m",
    season: "Mar to May, Sep to Nov",
    price: 550,
    icon: TbTent,
    image: WOMEN_TREK_PHOTO,
  },
  {
    title: "Annapurna Circuit Trek",
    days: "13 Days",
    href: "/trip/annapurna-circuit-trek",
    rating: 4.9,
    reviews: 77,
    difficulty: "Challenging",
    altitude: "5,416 m",
    season: "Mar to May, Sep to Nov",
    price: 850,
    icon: TbRoute,
    image: TREK_PHOTO,
  },
  {
    title: "Upper Mustang Trek",
    days: "12 Days",
    href: "/trip/upper-mustang-trek-nepal",
    rating: 4.8,
    reviews: 43,
    difficulty: "Moderate",
    altitude: "3,840 m",
    season: "Mar to Nov",
    price: 990,
    icon: TbFlag,
    image: WOMEN_TREK_PHOTO,
  },
];
