import {
  TbCamera,
  TbCompass,
  TbFlag,
  TbMapPin,
  TbMountain,
  TbSunrise,
  TbTent,
  TbWalk,
} from "react-icons/tb";

import { TREK_PHOTO, WOMEN_TREK_PHOTO } from "@/constant/photos";
import type { Trek } from "@/features/site/home/constant/trek";

export const shortTreks: Trek[] = [
  {
    title: "Ghorepani Poon Hill Trek",
    days: "4 Days",
    href: "/poonhill-trek-from-pokhara",
    rating: 4.8,
    reviews: 94,
    difficulty: "Easy to Moderate",
    altitude: "3,210 m",
    season: "All year",
    price: 295,
    icon: TbSunrise,
    image: TREK_PHOTO,
  },
  {
    title: "Mardi Himal Trek",
    days: "5 Days",
    href: "/mardi-himal-trek",
    rating: 4.9,
    reviews: 61,
    difficulty: "Moderate",
    altitude: "4,500 m",
    season: "Mar to Dec",
    price: 385,
    icon: TbMountain,
    image: WOMEN_TREK_PHOTO,
  },
  {
    title: "Australian Camp & Dhampus",
    days: "2 Days",
    href: "/australian-camp-day-hike",
    rating: 4.9,
    reviews: 31,
    difficulty: "Easy",
    altitude: "2,060 m",
    season: "All year",
    price: 145,
    icon: TbWalk,
    image: TREK_PHOTO,
  },
  {
    title: "Sarangkot TbSunrise & Paragliding",
    days: "1 Day",
    href: "/paragliding-in-pokhara-1",
    rating: 4.8,
    reviews: 58,
    difficulty: "Easy",
    altitude: "1,600 m",
    season: "All year",
    price: 120,
    icon: TbCompass,
    image: WOMEN_TREK_PHOTO,
  },
  {
    title: "Pokhara Peace Pagoda Hike",
    days: "Half Day",
    href: "/pokhara-peace-pagoda-hike",
    rating: 4.9,
    reviews: 40,
    difficulty: "Easy",
    altitude: "1,100 m",
    season: "All year",
    price: 65,
    icon: TbFlag,
    image: TREK_PHOTO,
  },
  {
    title: "Panchase Hill Day Hike",
    days: "1 Day",
    href: "/panchase-trek",
    rating: 4.8,
    reviews: 27,
    difficulty: "Moderate",
    altitude: "2,517 m",
    season: "Oct to May",
    price: 95,
    icon: TbTent,
    image: WOMEN_TREK_PHOTO,
  },
  {
    title: "Begnas Lake Day Hike",
    days: "1 Day",
    href: "/begnas-lake-day-hike",
    rating: 4.7,
    reviews: 22,
    difficulty: "Easy",
    altitude: "1,000 m",
    season: "All year",
    price: 55,
    icon: TbMapPin,
    image: TREK_PHOTO,
  },
  {
    title: "Naudanda Ridge Day Hike",
    days: "1 Day",
    href: "/naudanda-day-hike",
    rating: 4.6,
    reviews: 18,
    difficulty: "Easy",
    altitude: "1,500 m",
    season: "All year",
    price: 60,
    icon: TbCamera,
    image: WOMEN_TREK_PHOTO,
  },
];
